// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NneGGl1Bjni3cS07aUavApLrrdk08eU',
    appId: '1:134281827033:web:10fdefc83cadc38092e4c8',
    messagingSenderId: '134281827033',
    projectId: 'flutter-codelabs-f0a90',
    authDomain: 'flutter-codelabs-f0a90.firebaseapp.com',
    storageBucket: 'flutter-codelabs-f0a90.firebasestorage.app',
    measurementId: 'G-1F0T9GEX5C',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NneGGl1Bjni3cS07aUavApLrrdk08eU',
    appId: '1:134281827033:web:10fdefc83cadc38092e4c8',
    messagingSenderId: '134281827033',
    projectId: 'flutter-codelabs-f0a90',
    authDomain: 'flutter-codelabs-f0a90.firebaseapp.com',
    storageBucket: 'flutter-codelabs-f0a90.firebasestorage.app',
    measurementId: 'G-1F0T9GEX5C',
  );
}
